### ISSUE TITLE
unable to connect to couchbase lite and sync data

### ISSUE THREAD

**Issue by kanmadhu** [couchbase/couchbase-lite-java#104]
My couchbase is integrated to sync gateway. With the program that is on couchbase.com, couchbase lite is not able to connect to lite and sync data. Attached is the program used.

Using eclipse and following is the dependency added to POM file.

<dependencies>
              <dependency>
                             <groupId>com.couchbase.lite</groupId>
                             <artifactId>couchbase-lite-java</artifactId>
                             <version>1.4.1</version>
              </dependency>
</dependencies>
[main.txt.txt](https://github.com/couchbase/couchbase-lite-java/files/3030312/main.txt.txt)

**Comment by rajagp** [comment]
@kanmadhu - Installation related questions such as these are  probably better suited for our [Dev Forums ](https://forums.couchbase.com) .The GitHub repo is for tracking bugs . 

Here are some quick points to check - 
1) Can you confirm that you can reach the Sync Gateway at `http://localhost:4984/` . What do you see?
2) Can you share the output of [Couchbase Lite logs](https://docs.couchbase.com/couchbase-lite/1.4/java.html#global-logging-settings) and the [Sync Gateway logs](https://docs.couchbase.com/sync-gateway/2.1/logging.html#log-rotation-configuration). You can collect the logs from logcat output.

I'd also suggest reposting this question to the dev forums with the above requested info.

**Comment by kanmadhu** [comment]
port 4985 output:
{   
   - ADMIN: true,
   - couchdb: "Welcome",
   - vendor: {      
      - name: "Couchbase Sync Gateway",
      - version: "2.1"
},
   - version: "Couchbase Sync Gateway/2.1.2(2;35fe28e)"
}

port 4984 output:
{   
   - couchdb: "Welcome",
   - vendor: {      
      - name: "Couchbase Sync Gateway",
      - version: "2.1"
},
   - version: "Couchbase Sync Gateway/2.1.2(2;35fe28e)"
}


Library not found: /native/windows/amd64/sqlcipher.dllApr 01, 2019 9:56:42 AM com.couchbase.lite.util.SystemLogger eSEVERE: CBLite: Cannot find library: sqlcipherLibrary not found: /native/windows/amd64/sqlite3.dllApr 01, 2019 9:56:42 AM com.couchbase.lite.util.SystemLogger eSEVERE: CBLite: Cannot find library: sqlite3Apr 01, 2019 9:56:42 AM com.couchbase.lite.util.SystemLogger eSEVERE: Database: Cannot load native libraryJavaSQLiteStorageEngineLibrary not found: /native/windows/amd64/sqlcipher.dllApr 01, 2019 9:56:42 AM com.couchbase.lite.util.SystemLogger eSEVERE: CBLite: Cannot find library: sqlcipherLibrary not found: /native/windows/amd64/sqlite3.dllApr 01, 2019 9:56:42 AM com.couchbase.lite.util.SystemLogger eSEVERE: CBLite: Cannot find library: sqlite3Apr 01, 2019 9:56:42 AM com.couchbase.lite.util.SystemLogger eSEVERE: Database: Cannot load native libraryException in thread "main" java.lang.UnsatisfiedLinkError: com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativeOpen(Ljava/lang/String;ILjava/lang/String;ZZ)J at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.nativeOpen(Native Method) at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:194) at com.couchbase.lite.internal.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:178) at com.couchbase.lite.internal.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:461) at com.couchbase.lite.internal.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:191) at com.couchbase.lite.internal.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:183) at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:820) at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:803) at com.couchbase.lite.internal.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:698) at com.couchbase.lite.storage.SQLiteStorageEngineBase.open(SQLiteStorageEngineBase.java:70) at com.couchbase.lite.store.SQLiteStore.open(SQLiteStore.java:186) at com.couchbase.lite.Database.open(Database.java:1333) at com.couchbase.lite.Manager.openDatabase(Manager.java:341) at com.couchbase.lite.Manager.getDatabase(Manager.java:305) at CouchbaseLite.CouchbaseLite.Main.main(Main.java:34)



    On Monday, April 1, 2019, 2:45:55 PM EDT, Priya Rajagopal <notifications@github.com> wrote:  
 
 
@kanmadhu - Installation related questions such as these are probably better suited for our Dev Forums  .The GitHub repo is for tracking bugs .

Here are some quick points to check -
   
   - Can you confirm that you can reach the Sync Gateway at http://localhost:4984/ . What do you see?
   - Can you share the output of Couchbase Lite logs and the Sync Gateway logs. You can collect the logs from logcat output.

I'd also suggest reposting this question to the dev forums with the above requested info.

**Comment by rajagp** [comment]
@kanmadhu As indicated in the error output, the sqlCIpher library is missed.
Please add the relevant dependencies to your pom.xml file
`couchbase-lite-java-sqlcipher`

Also, for future release, please refer to the install instructions in this [guide](https://docs.couchbase.com/couchbase-lite/1.4/java.html#getting-started)

**Comment by malarky** [comment]
Hi @kanmadhu, can you try increasing the version from 1.4.1 to 1.4.4?

**Comment by rajagp** [comment]
@kanmadhu   Following up on your questions, as indicated in my earlier post, you will have to import the relevant library. If specifying dependency in pom.xml does not import dependencies correctly, you can import the `couchbase-lite-java-sqlcipher` library from maven through project settings.

Here are the screenshots from VS on macOS. You will have to do the equivalent on Windows (which from your logs appears to be the platform that you are running it on). As you can see from screenshots, this works for 1.4.1 or 1.4.4 - preferable to go with the latest.

Step 1:
<img width="919" alt="step1" src="https://user-images.githubusercontent.com/645251/55512953-7b63c380-5632-11e9-8ad2-0a688aec233b.png">

Step 2:
<img width="920" alt="step2" src="https://user-images.githubusercontent.com/645251/55512955-7ef74a80-5632-11e9-92ff-5b7f9825d214.png">

Expected (project viewer )- confirm library is listed:
<img width="619" alt="step3" src="https://user-images.githubusercontent.com/645251/55512971-8a4a7600-5632-11e9-9326-96c3cbab5448.png">


I was able to build and run a sample app successfully.

BTW, the sample in the docs have errors in them and we will look into fixing those . If you are interested, here is a [sample](https://gist.github.com/rajagp/14ef1baf3b714f7c4f84fbe947300716)
