### ISSUE TITLE
unable to execute unit tests on windows

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/couchbase-lite-java#67]
```
15:55:10.096 [QUIET] [system.out] 15:55:10.094 [INFO] [org.gradle.api.internal.tasks.testing.worker.TestWorker] Gradle Test Executor 1 started executing tests.
15:55:10.161 [DEBUG] [TestEventLogger] 
15:55:10.161 [DEBUG] [TestEventLogger] Gradle Test Executor 1 STARTED
15:55:10.164 [QUIET] [system.out] 15:55:10.164 [DEBUG] [org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor] Executing test class com.couchbase.lite.ApiTest
15:55:10.165 [DEBUG] [TestEventLogger] 
15:55:10.165 [DEBUG] [TestEventLogger] com.couchbase.lite.ApiTest STARTED
15:55:10.320 [DEBUG] [TestEventLogger] 
15:55:10.320 [DEBUG] [TestEventLogger] com.couchbase.lite.ApiTest > testDatabaseCompaction STARTED
15:55:10.342 [DEBUG] [TestEventLogger] 
15:55:10.343 [DEBUG] [TestEventLogger] com.couchbase.lite.ApiTest > testDatabaseCompaction STANDARD_ERROR
15:55:10.343 [DEBUG] [TestEventLogger]     Aug 18, 2015 3:55:10 PM com.couchbase.lite.util.SystemLogger i
15:55:10.345 [DEBUG] [TestEventLogger]     INFO: Database: Starting Manager version: devbuild
15:55:10.346 [DEBUG] [TestEventLogger]     Aug 18, 2015 3:55:10 PM com.couchbase.lite.util.SystemLogger w
15:55:10.347 [DEBUG] [TestEventLogger]     WARNING: Database: mustExist is true and db (cblite-test) does not exist
15:55:10.347 [DEBUG] [TestEventLogger]     Aug 18, 2015 3:55:10 PM com.couchbase.lite.util.SystemLogger v
15:55:10.347 [DEBUG] [TestEventLogger]     FINER: Database: Opening com.couchbase.lite.Database[D:\temp\src\couchbase-lite-java\couchbaselitetest\test\cblite-test.cblite2]
15:55:10.352 [DEBUG] [TestEventLogger]     Aug 18, 2015 3:55:10 PM com.couchbase.lite.util.SystemLogger e
15:55:10.353 [DEBUG] [TestEventLogger]     SEVERE: Native: Library not found: /native/windows/amd64/CouchbaseLiteJavaNative.dll
15:55:10.353 [DEBUG] [TestEventLogger]     Aug 18, 2015 3:55:10 PM com.couchbase.lite.util.SystemLogger e
15:55:10.353 [DEBUG] [TestEventLogger]     SEVERE: Native: Error loading library: CouchbaseLiteJavaNative
15:55:10.353 [DEBUG] [TestEventLogger]     java.lang.NullPointerException
15:55:10.353 [DEBUG] [TestEventLogger]     	at com.couchbase.lite.util.NativeUtils.loadLibrary(NativeUtils.java:45)
15:55:10.353 [DEBUG] [TestEventLogger]     	at com.couchbase.lite.storage.JavaSQLiteStorageEngine.<clinit>(JavaSQLiteStorageEngine.java:125)
15:55:10.353 [DEBUG] [TestEventLogger]     	at com.couchbase.lite.storage.JavaSQLiteStorageEngineFactory.createStorageEngine(JavaSQLiteStorageEngineFactory.java:6)
15:55:10.353 [DEBUG] [TestEventLogger]     	at com.couchbase.lite.store.SQLiteStore.open(SQLiteStore.java:158)
15:55:10.354 [DEBUG] [TestEventLogger]     	at com.couchbase.lite.Database.open(Database.java:1019)
15:55:10.354 [DEBUG] [TestEventLogger]     	at com.couchbase.lite.Manager.getDatabase(Manager.java:251)
15:55:10.354 [DEBUG] [TestEventLogger]     	at com.couchbase.lite.LiteTestCase.ensureEmptyDatabase(LiteTestCase.java:128)
15:55:10.354 [DEBUG] [TestEventLogger]     	at com.couchbase.lite.LiteTestCase.startDatabase(LiteTestCase.java:113)
15:55:10.354 [DEBUG] [TestEventLogger]     	at com.couchbase.lite.LiteTestCase.setUp(LiteTestCase.java:72)
15:55:10.354 [DEBUG] [TestEventLogger]     	at junit.framework.TestCase.runBare(TestCase.java:139)
15:55:10.354 [DEBUG] [TestEventLogger]     	at junit.framework.TestResult$1.protect(TestResult.java:122)
15:55:10.355 [DEBUG] [TestEventLogger]     	at junit.framework.TestResult.runProtected(TestResult.java:142)
15:55:10.355 [DEBUG] [TestEventLogger]     	at junit.framework.TestResult.run(TestResult.java:125)
15:55:10.355 [DEBUG] [TestEventLogger]     	at junit.framework.TestCase.run(TestCase.java:129)
15:55:10.355 [DEBUG] [TestEventLogger]     	at junit.framework.TestSuite.runTest(TestSuite.java:255)
15:55:10.355 [DEBUG] [TestEventLogger]     	at junit.framework.TestSuite.run(TestSuite.java:250)
15:55:10.355 [DEBUG] [TestEventLogger]     	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
15:55:10.355 [DEBUG] [TestEventLogger]     	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
15:55:10.355 [DEBUG] [TestEventLogger]     	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
15:55:10.355 [DEBUG] [TestEventLogger]     	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
15:55:10.356 [DEBUG] [TestEventLogger]     	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
15:55:10.356 [DEBUG] [TestEventLogger]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:55:10.356 [DEBUG] [TestEventLogger]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
15:55:10.356 [DEBUG] [TestEventLogger]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
15:55:10.356 [DEBUG] [TestEventLogger]     	at java.lang.reflect.Method.invoke(Method.java:597)
15:55:10.356 [DEBUG] [TestEventLogger]     	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
15:55:10.356 [DEBUG] [TestEventLogger]     	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
15:55:10.356 [DEBUG] [TestEventLogger]     	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
15:55:10.356 [DEBUG] [TestEventLogger]     	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
15:55:10.357 [DEBUG] [TestEventLogger]     	at $Proxy2.processTestClass(Unknown Source)
15:55:10.357 [DEBUG] [TestEventLogger]     	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
15:55:10.357 [DEBUG] [TestEventLogger]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:55:10.357 [DEBUG] [TestEventLogger]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
15:55:10.357 [DEBUG] [TestEventLogger]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
15:55:10.357 [DEBUG] [TestEventLogger]     	at java.lang.reflect.Method.invoke(Method.java:597)
15:55:10.357 [DEBUG] [TestEventLogger]     	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
15:55:10.357 [DEBUG] [TestEventLogger]     	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
15:55:10.357 [DEBUG] [TestEventLogger]     	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
15:55:10.357 [DEBUG] [TestEventLogger]     	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
15:55:10.358 [DEBUG] [TestEventLogger]     	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
15:55:10.358 [DEBUG] [TestEventLogger]     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
15:55:10.358 [DEBUG] [TestEventLogger]     	at java.lang.Thread.run(Thread.java:662)
15:55:10.358 [DEBUG] [TestEventLogger] 
15:55:10.380 [DEBUG] [TestEventLogger] 
15:55:10.381 [DEBUG] [TestEventLogger] com.couchbase.lite.ApiTest > testDatabaseCompaction FAILED
15:55:10.381 [DEBUG] [TestEventLogger]     java.lang.UnsatisfiedLinkError: com.couchbase.lite.storage.JavaSQLiteStorageEngine._open(Ljava/lang/String;)J
15:55:10.381 [DEBUG] [TestEventLogger]         at com.couchbase.lite.storage.JavaSQLiteStorageEngine._open(Native Method)
15:55:10.381 [DEBUG] [TestEventLogger]         at com.couchbase.lite.storage.JavaSQLiteStorageEngine.access$100(JavaSQLiteStorageEngine.java:8)
15:55:10.381 [DEBUG] [TestEventLogger]         at com.couchbase.lite.storage.JavaSQLiteStorageEngine$Connection.<init>(JavaSQLiteStorageEngine.java:23)
15:55:10.381 [DEBUG] [TestEventLogger]         at com.couchbase.lite.storage.JavaSQLiteStorageEngine$ConnectionPool.start(JavaSQLiteStorageEngine.java:46)
15:55:10.381 [DEBUG] [TestEventLogger]         at com.couchbase.lite.storage.JavaSQLiteStorageEngine.open(JavaSQLiteStorageEngine.java:138)
15:55:10.382 [DEBUG] [TestEventLogger]         at com.couchbase.lite.store.SQLiteStore.open(SQLiteStore.java:161)
15:55:10.382 [DEBUG] [TestEventLogger]         at com.couchbase.lite.Database.open(Database.java:1019)
15:55:10.382 [DEBUG] [TestEventLogger]         at com.couchbase.lite.Manager.getDatabase(Manager.java:251)
15:55:10.382 [DEBUG] [TestEventLogger]         at com.couchbase.lite.LiteTestCase.ensureEmptyDatabase(LiteTestCase.java:128)
15:55:10.382 [DEBUG] [TestEventLogger]         at com.couchbase.lite.LiteTestCase.startDatabase(LiteTestCase.java:113)
15:55:10.382 [DEBUG] [TestEventLogger]         at com.couchbase.lite.LiteTestCase.setUp(LiteTestCase.java:72)
15:55:10.382 [DEBUG] [TestEventLogger]         at junit.framework.TestCase.runBare(TestCase.java:139)
15:55:10.382 [DEBUG] [TestEventLogger]         at junit.framework.TestResult$1.protect(TestResult.java:122)
15:55:10.382 [DEBUG] [TestEventLogger]         at junit.framework.TestResult.runProtected(TestResult.java:142)
15:55:10.382 [DEBUG] [TestEventLogger]         at junit.framework.TestResult.run(TestResult.java:125)
15:55:10.382 [DEBUG] [TestEventLogger]         at junit.framework.TestCase.run(TestCase.java:129)
15:55:10.383 [DEBUG] [TestEventLogger]         at junit.framework.TestSuite.runTest(TestSuite.java:255)
15:55:10.383 [DEBUG] [TestEventLogger]         at junit.framework.TestSuite.run(TestSuite.java:250)
15:55:10.383 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
15:55:10.383 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
15:55:10.383 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
15:55:10.383 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
15:55:10.383 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
15:55:10.383 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:55:10.383 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
15:55:10.383 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
15:55:10.383 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:597)
15:55:10.384 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
15:55:10.384 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
15:55:10.384 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
15:55:10.384 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
15:55:10.384 [DEBUG] [TestEventLogger]         at $Proxy2.processTestClass(Unknown Source)
15:55:10.384 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
15:55:10.384 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:55:10.384 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
15:55:10.385 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
15:55:10.385 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:597)
15:55:10.385 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
15:55:10.385 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
15:55:10.385 [DEBUG] [TestEventLogger]         at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
15:55:10.385 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
15:55:10.385 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
15:55:10.385 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
15:55:10.385 [DEBUG] [TestEventLogger]         at java.lang.Thread.run(Thread.java:662)
15:55:10.387 [DEBUG] [TestEventLogger] 
```

```
$ ./gradlew test --stacktrace --debug > output
15:55:11.859 [ERROR] [org.gradle.api.internal.tasks.testing.logging.TestCountLog
ger]
360 tests completed, 355 failed
15:55:12.175 [ERROR] [org.gradle.BuildExceptionReporter]
15:55:12.176 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed w
ith an exception.
15:55:12.177 [ERROR] [org.gradle.BuildExceptionReporter]
15:55:12.177 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
15:55:12.178 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for ta
sk ':test'.
15:55:12.178 [ERROR] [org.gradle.BuildExceptionReporter] > There were failing te
sts. See the report at: file:///D:/temp/src/couchbase-lite-java/build/reports/te
sts/index.html
15:55:12.179 [ERROR] [org.gradle.BuildExceptionReporter]
15:55:12.180 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
15:55:12.181 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.Ta
skExecutionException: Execution failed for task ':test'.
15:55:12.181 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ap
i.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActi
onsTaskExecuter.java:69)
15:55:12.182 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ap
i.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTask
Executer.java:46)
15:55:12.182 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ap
i.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecuti
onAnalysisTaskExecuter.java:35)
15:55:12.183 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ap
i.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExec
uter.java:64)
15:55:12.183 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ap
i.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter
.java:58)
15:55:12.183 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ap
i.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySou
rceFilesTaskExecuter.java:42)
15:55:12.184 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ap
i.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoA
ctionsExecuter.java:52)
15:55:12.184 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ap
i.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter
.java:53)
15:55:12.185 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ap
i.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOn
ceTaskExecuter.java:43)
15:55:12.186 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ap
i.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)

15:55:12.186 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ex
ecution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(Abstra
ctTaskPlanExecutor.java:79)
15:55:12.187 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ex
ecution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(Abstra
ctTaskPlanExecutor.java:63)
15:55:12.187 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ex
ecution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPl
anExecutor.java:51)
15:55:12.187 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ex
ecution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:2
3)
15:55:12.188 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ex
ecution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java
:88)
15:55:12.188 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ex
ecution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)

15:55:12.189 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ex
ecution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
15:55:12.189 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ex
ecution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
15:55:12.189 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ex
ecution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
15:55:12.190 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ex
ecution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
15:55:12.190 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ex
ecution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
15:55:12.191 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ex
ecution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
15:55:12.191 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.in
itialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)

15:55:12.191 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.in
itialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
15:55:12.192 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.in
itialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
15:55:12.193 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.la
uncher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBui
ldActionExecuter.java:80)
15:55:12.193 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.la
uncher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
15:55:12.200 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.la
uncher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
15:55:12.201 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.la
uncher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.ja
va:36)
15:55:12.202 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.la
uncher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.ja
va:26)
15:55:12.203 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.la
uncher.cli.RunBuildAction.run(RunBuildAction.java:51)
15:55:12.203 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.in
ternal.Actions$RunnableActionAdapter.execute(Actions.java:171)
15:55:12.203 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.la
uncher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActio
nFactory.java:237)
15:55:12.204 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.la
uncher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActio
nFactory.java:210)
15:55:12.204 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.la
uncher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:
35)
15:55:12.216 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.la
uncher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:
24)
15:55:12.217 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.la
uncher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory
.java:206)
15:55:12.218 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.la
uncher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory
.java:169)
15:55:12.219 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.la
uncher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
15:55:12.220 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.la
uncher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
15:55:12.220 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.la
uncher.Main.doAction(Main.java:33)
15:55:12.221 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.la
uncher.bootstrap.EntryPoint.run(EntryPoint.java:45)
15:55:12.221 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.la
uncher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
15:55:12.233 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.la
uncher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
15:55:12.233 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.la
uncher.GradleMain.main(GradleMain.java:23)
15:55:12.234 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wr
apper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
15:55:12.234 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wr
apper.WrapperExecutor.execute(WrapperExecutor.java:127)
15:55:12.235 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.wr
apper.GradleWrapperMain.main(GradleWrapperMain.java:58)
15:55:12.235 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.a
pi.GradleException: There were failing tests. See the report at: file:///D:/temp
/src/couchbase-lite-java/build/reports/tests/index.html
15:55:12.236 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ap
i.tasks.testing.Test.handleTestFailures(Test.java:1111)
15:55:12.236 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ap
i.tasks.testing.Test.executeTests(Test.java:542)
15:55:12.236 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.in
ternal.reflect.JavaMethod.invoke(JavaMethod.java:63)
15:55:12.237 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ap
i.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskActio
n.doExecute(AnnotationProcessingTaskFactory.java:218)
15:55:12.251 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ap
i.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskActio
n.execute(AnnotationProcessingTaskFactory.java:211)
15:55:12.252 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ap
i.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskActio
n.execute(AnnotationProcessingTaskFactory.java:200)
15:55:12.254 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ap
i.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
15:55:12.254 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ap
i.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
15:55:12.255 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ap
i.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActio
nsTaskExecuter.java:80)
15:55:12.255 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.ap
i.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActi
onsTaskExecuter.java:61)
15:55:12.256 [ERROR] [org.gradle.BuildExceptionReporter]        ... 47 more
15:55:12.256 [ERROR] [org.gradle.BuildExceptionReporter]
```

output
https://friendpaste.com/7m0W4j7dhYDwUJi4CsfQvF

**Comment by hideki** [comment]
@andreibaranouski 

Did you build couchbase-lite-java-native for Windows? Error occurs when load native library.

For v1.1.0, I tested couchbase-lite-java on Windows. And it worked fine.
What is your test environment?

Thanks!

**Comment by andreibaranouski** [comment]
Hi @hideki,

I tried to build couchbase-lite-java-native project according to README
```
$ gradlew clean
$ gradlew build
``` 
and also tried via gradlew.ba
```
D:\temp\src\couchbase-lite-java\libraries\couchbase-lite-java-native>gradlew.bat clean build
:libraries:couchbase-lite-java-native:clean
:libraries:couchbase-lite-java-native:compileJava
:libraries:couchbase-lite-java-native:processResources UP-TO-DATE
:libraries:couchbase-lite-java-native:classes
:libraries:couchbase-lite-java-native:jar
:libraries:couchbase-lite-java-native:sourcesJar
:libraries:couchbase-lite-java-native:assemble
:libraries:couchbase-lite-java-native:compileTestJava UP-TO-DATE
:libraries:couchbase-lite-java-native:processTestResources UP-TO-DATE
:libraries:couchbase-lite-java-native:testClasses UP-TO-DATE
:libraries:couchbase-lite-java-native:test UP-TO-DATE
:libraries:couchbase-lite-java-native:check UP-TO-DATE
:libraries:couchbase-lite-java-native:build

BUILD SUCCESSFUL

Total time: 3.751 secs
```
so, there are no any errors but native libraries are not built
btw: I don't have VS installed on the host. will try to do the same steps where VS has been installed

**Comment by hideki** [comment]
@andreibaranouski,
VC is requirement to build CBL Java on Windows. Please use latest VC.

**Comment by hideki** [comment]
Hi @andreibaranouski,
Can you solve this problem?

**Comment by jamiltz** [comment]
Piggybacking on this thread as I'm trying to build java-core on windows as well but for a different use case. Aiming to use java-core in a webview for hybrid apps on windows tablets. Are there instructions for building java-core in Visual Studio? If not, it'd be great to help me out with the basic steps and I'll add them to a wiki page from there.

**Comment by hideki** [comment]
@jamiltz Just needs to follow instruction of README see: https://github.com/couchbase/couchbase-lite-java

Please install latest Visual Studio to compile couchbase-lite-java-native (https://github.com/couchbase/couchbase-lite-java-native)

**Comment by andreibaranouski** [comment]
it works fine if for VS2015 apply workaround  https://github.com/couchbase/couchbase-lite-java-native/issues/23

```
$ git diff
diff --git a/build.gradle b/build.gradle
index f38e33f..5c32083 100644
--- a/build.gradle
+++ b/build.gradle
@@ -4,6 +4,9 @@ apply plugin: 'maven'

 version = System.getenv("MAVEN_UPLOAD_VERSION")

+def VS_2015_INCLUDE_DIR = "C:/Program Files (x86)/Windows Kits/10/Include/10.0.10150.0/ucrt"
+def VS_2015_LIB_DIR = "C:/Program Files (x86)/Windows Kits/10/Lib/10.0.10150.0/ucrt"
+
 model {
     platforms {
         osx_x86 {
@@ -75,8 +78,15 @@ libraries {
                 cCompiler.args '-I', "${org.gradle.internal.jvm.Jvm.current().javaHome}/include"
                 cCompiler.args '-I', "${org.gradle.internal.jvm.Jvm.current().javaHome}/include/linux"
             } else if (targetPlatform.operatingSystem.windows) {
+               cCompiler.args "-I" + VS_2015_INCLUDE_DIR
                 cCompiler.args "-I${org.gradle.internal.jvm.Jvm.current().javaHome}/include"
                 cCompiler.args "-I${org.gradle.internal.jvm.Jvm.current().javaHome}/include/win32"
+                if(targetPlatform.architecture.name == "x86") {
+                    linker.args "/LIBPATH:" + VS_2015_LIB_DIR + "/x86"
+                }
+                else if(targetPlatform.architecture.name == "x86_64" || targetPlatform.architecture.name == "amd64") {
+                    linker.args "/LIBPATH:" + VS_2015_LIB_DIR + "/x64"
+                }
             }
         }
     }
(END)
```
