### ISSUE TITLE
Test Failure: testRetryQueueDeadlock

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java#95]
```
com.couchbase.lite.replicator.RemoteRequestTest > testRetryQueueDeadlock FAILED
    junit.framework.AssertionFailedError at RemoteRequestTest.java:309
```

Note: Observed with OSX, Windows. But not with Linux

**Comment by hideki** [comment]
```
SEVERE: MockWebServer[54379] connection from /127.0.0.1 crashed
java.lang.IndexOutOfBoundsException: Index: 0, Size: -1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.remove(ArrayList.java:492)
	at okhttp3.Headers$Builder.removeAll(Headers.java:288)
	at okhttp3.mockwebserver.MockResponse.removeHeader(MockResponse.java:151)
	at okhttp3.mockwebserver.MockResponse.setHeader(MockResponse.java:139)
	at com.couchbase.lite.mockserver.MockDispatcher.addHeaders(MockDispatcher.java:299)
	at com.couchbase.lite.mockserver.MockDispatcher.dispatch(MockDispatcher.java:125)
	at okhttp3.mockwebserver.MockWebServer$4.processOneRequest(MockWebServer.java:508)
	at okhttp3.mockwebserver.MockWebServer$4.processConnection(MockWebServer.java:464)
	at okhttp3.mockwebserver.MockWebServer$4.execute(MockWebServer.java:404)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Jan 11, 2017 1:11:47 PM okhttp3.mockwebserver.MockWebServer$4 execute
SEVERE: MockWebServer[54379] connection from /127.0.0.1 crashed
java.lang.NegativeArraySizeException
	at okhttp3.Headers.<init>(Headers.java:53)
	at okhttp3.Headers.<init>(Headers.java:49)
	at okhttp3.Headers$Builder.build(Headers.java:337)
	at okhttp3.mockwebserver.MockResponse.getHeaders(MockResponse.java:95)
	at okhttp3.mockwebserver.MockWebServer.writeHttpResponse(MockWebServer.java:706)
	at okhttp3.mockwebserver.MockWebServer.access$1900(MockWebServer.java:101)
	at okhttp3.mockwebserver.MockWebServer$4.processOneRequest(MockWebServer.java:527)
	at okhttp3.mockwebserver.MockWebServer$4.processConnection(MockWebServer.java:464)
	at okhttp3.mockwebserver.MockWebServer$4.execute(MockWebServer.java:404)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Jan 11, 2017 1:11:47 PM okhttp3.mockwebserver.MockWebServer$4 execute
SEVERE: MockWebServer[54379] connection from /127.0.0.1 crashed
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.remove(ArrayList.java:501)
	at okhttp3.Headers$Builder.removeAll(Headers.java:288)
	at okhttp3.mockwebserver.MockResponse.removeHeader(MockResponse.java:151)
	at okhttp3.mockwebserver.MockResponse.setHeader(MockResponse.java:139)
	at com.couchbase.lite.mockserver.MockDispatcher.addHeaders(MockDispatcher.java:299)
	at com.couchbase.lite.mockserver.MockDispatcher.dispatch(MockDispatcher.java:125)
	at okhttp3.mockwebserver.MockWebServer$4.processOneRequest(MockWebServer.java:508)
	at okhttp3.mockwebserver.MockWebServer$4.processConnection(MockWebServer.java:464)
	at okhttp3.mockwebserver.MockWebServer$4.execute(MockWebServer.java:404)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Jan 11, 2017 1:11:47 PM okhttp3.mockwebserver.MockWebServer$4 execute
SEVERE: MockWebServer[54379] connection from /127.0.0.1 crashed
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.add(ArrayList.java:459)
	at okhttp3.Headers$Builder.addLenient(Headers.java:279)
	at okhttp3.Headers$Builder.add(Headers.java:271)
	at okhttp3.mockwebserver.MockResponse.addHeader(MockResponse.java:121)
	at okhttp3.mockwebserver.MockResponse.setHeader(MockResponse.java:140)
	at com.couchbase.lite.mockserver.MockDispatcher.addHeaders(MockDispatcher.java:299)
	at com.couchbase.lite.mockserver.MockDispatcher.dispatch(MockDispatcher.java:125)
	at okhttp3.mockwebserver.MockWebServer$4.processOneRequest(MockWebServer.java:508)
	at okhttp3.mockwebserver.MockWebServer$4.processConnection(MockWebServer.java:464)
	at okhttp3.mockwebserver.MockWebServer$4.execute(MockWebServer.java:404)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by hideki** [comment]
OkHttp3's `Headers.Builder` is not thread-safe.
https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/Headers.java#L284-L293

And `MockDispatcher` is not thread-safe, it causes a threading issue in case multiple threads calls `MockDispatcher.dispatch()` or other methods.

**Comment by hideki** [comment]
PR: https://github.com/couchbase/couchbase-lite-android/pull/1058
